# Generated by Django 4.0.4 on 2022-05-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0003_contect_delete_contectform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contect',
            new_name='Contect_us',
        ),
    ]
