# Generated by Django 4.0.4 on 2022-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0006_rename_email_address_contect_us_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect_us',
            name='msg',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contect_us',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
