# Generated by Django 4.0.4 on 2022-05-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0007_alter_contect_us_msg_alter_contect_us_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contect_okk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('msg', models.TextField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='AddBook',
        ),
    ]
